### ISSUE TITLE
gcloud_requests dependency has old google-cloud dependencies

### ISSUE THREAD

**Issue by JorinTielen** [Bogdanp/anom-py#15]
`gcloud_requests` has a hard dependency on an old version of `google-cloud-core>=0.24,<0.25`, which is annoying if you want to use `google-cloud-*` libraries released after ~June 2017. For example when someone wants to use `google-cloud-logging==1.8.0` this will lead to a pipenv version resolution failure. It could also lead to other errors when people don't use pipenv, because of libraries expecting different versions of `google-cloud-core`. 

As [`google-cloud-datastore` uses requests under the hood](https://github.com/googleapis/google-cloud-python/commit/7d1161f70744c0dbbe67a3f472ea95667eaafe50) now, i don't see the use for `gcloud_requests` anymore (I don't think the maintainers do either, it hasn't been updated in over a year). So it would be nice if anom-py could use the latest google-cloud dependency.

I attempted to remove the dependency and use the latest `google-cloud-datastore` on [my fork](https://github.com/JorinTielen/anom-py/commit/dfa8a61aadeb041a3d8dda03932b5803bca5b8d0). Even though the tests pass, when running on google app engine it breaks, and i have no clue why (the worker just crashes / times out, so i don't have a trace or anything). So something probably is still wrong there, and that's why i just decided to make an issue instead of an PR because you might be able to figure it out.

**Comment by Bogdanp** [comment]
As one of the authors of `gcloud_requests`, I can tell you it does more than just replace the transport with Requests. It also implements exponential backoff and retry on the various types of failures that can result from Datastore, as well as eager credential refreshing and possibly a couple other things I'm forgetting.

I think the best move here would be to update gcloud_requests so that it is compatible with the latest versions of the google-cloud libraries. I'm sure LeadPages would happily accept a PR for that and, if not, we can always publish and use a fork (or we could even vendor it into this library).

**Comment by Bogdanp** [comment]
Looks like the Leadpages folks are now working on updating the library at https://github.com/LeadPages/gcloud_requests/pull/22 so we can just pull in that version once it's released.
